name: Test - Clair in CI DB

# This workflow builds latest database version of clair-in-ci and
# pushes it to app-studio registry ahoj

on:
  #schedule:
  #  - cron: '*/15 * * * *'
  pull_request:
    branches: [ main ]

env:
  REGISTRY: quay.io/redhat-appstudio
  IMAGE_NAME: clair-in-ci
  LATEST_TAG: latest
  PREVIOUS_TAG: previous
  GITHUB_TOKEN: ${{ secrets.CLAIR_TEST }}
  PR_STATE: ""
  PR_NUMBER: 0
  

jobs:
  test:
    name: Build the new image
    runs-on: ubuntu-20.04

    steps:
    - name: Check out repository code
      uses: actions/checkout@v3
      with:
        ref: main
    - name: create pull request
      run: |
          echo "Check if PR is already created."
          PR_NUMBER=$(gh pr list --state all --label clair-db --json number | jq -r '.[0] | .number')
          if [ -z "$PR_NUMBER" ] || [ "$PR_NUMBER" == null ]; then
            echo "No existing PR with label clair-db was found. Creating a new PR..."
            gh pr create -B main -H alpha-v1 --title 'Merge alpha-v1 into main for clair-db' --body 'Created by Github action' --label clair-db
            sleep 5
            PR_NUMBER=$(gh pr list --state all --label clair-db --json number | jq -r '.[0] | .number')
          fi
          PR_STATE=$(gh pr view $PR_NUMBER --json state | jq -r '.state')
          if [ "$PR_STATE" != "OPEN" ]; then
            echo "$PR_NUMBER is $PR_STATE, reopening it now."
            gh pr reopen $PR_NUMBER
            echo "PR number: $PR_NUMBER has been opened."
            sleep 5
          else
            git commit --allow-empty -m "Empty-commit"
            git push origin alpha-v1 -f
          fi
