name: Test - Clair in CI DB

# This workflow builds latest database version of clair-in-ci and
# pushes it to app-studio registry ahoj

on:
  #schedule:
  #  - cron: '*/15 * * * *'
  pull_request:
    branches: [ main ]

env:
  REGISTRY: quay.io/redhat-appstudio
  IMAGE_NAME: clair-in-ci
  LATEST_TAG: latest
  PREVIOUS_TAG: previous
  GITHUB_TOKEN: ${{ secrets.CLAIR_TEST }}
  IS_CREATED: false


jobs:
  test:
    name: Build the new image
    runs-on: ubuntu-20.04

    steps:
    - name: Check out repository code
      uses: actions/checkout@v3
      with:
        ref: main
    - name: say hello
      run: echo "hello"
    - name: create pull request
      run: |
        gh pr create -B main -H simple --title 'Merge simple into main' --body 'Created by Github action'
        if [ $? != 0 ]; then
          echo "PR is already created"
          gh pr view 7
        else
          echo "New PR has been created"
        fi
