name: Test - Clair in CI DB

# This workflow builds latest database version of clair-in-ci and
# pushes it to app-studio registry ahoj

on:
  #schedule:
  #  - cron: '*/15 * * * *'
  pull_request:
    branches: [ main ]

env:
  REGISTRY: quay.io/redhat-appstudio
  IMAGE_NAME: clair-in-ci
  LATEST_TAG: latest
  PREVIOUS_TAG: previous
  GITHUB_TOKEN: ${{ secrets.CLAIR_TEST }}
  IS_CREATED: false
  OUTPUT_JSON: ""
  PR_NUMBER: 0
  

#gh pr create -B main -H tkn-sanity --title 'Merge tkn-sanity into main for clair-db' --body 'Created by Github action' --label clair-db
#if [ $? != 0 ]; then
jobs:
  test:
    name: Build the new image
    runs-on: ubuntu-20.04

    steps:
    - name: Check out repository code
      uses: actions/checkout@v3
      with:
        ref: main
    - name: say hello
      run: echo "hello"
    - name: create pull request
      run: |
          echo "PR is already created"
          PR_NUMBER=$(gh pr list --label clair-db --json number | jq -r '.[] | .number')
          echo $PR_NUMBER
          if [ $PR_NUMBER -eq 0]; then
            echo "creating new PR"
            gh pr create -B main -H tkn-sanity --title 'Merge tkn-sanity into main for clair-db' --body 'Created by Github action' --label clair-db
          fi
          OUTPUT_JSON=$(gh pr view $PR_NUMBER --json state | jq -r '.state')
          echo $OUTPUT_JSON
          if [ "$OUTPUT_JSON" == "OPEN" ]; then
            gh pr close $PR_NUMBER
            echo "PR has been closed"
          else
            gh pr reopen $PR_NUMBER
            echo "PR has been opened"
          fi
